server:
  port: 8081

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:29092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.jesterino.notification.event.TaskCreatedEvent
        spring.json.use.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted

  prometheus:
    metrics:
      export:
        enabled: true

logging:
  file:
    name: /var/log/notification/application.log